src/java/send/sms/az/model/BulkSMS.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package send.sms.az.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * @author rasha_000
 */
public class BulkSMS extends BaseModel implements Serializable {

    private BigDecimal sendFrom;
    private String comment;
    private Books addressBooks;
    private String message;
    private BigDecimal validPeriod;
    private BigDecimal offset;
    private BigDecimal maxCount;
    private BigDecimal batchSize;
    private BigDecimal batchInterval;
    private BigDecimal sendAt;
    private Date sendDate;
    private BigDecimal userID;
    private int smsCharSize = 0;
    private String numberCount;

    public BulkSMS() {
        addressBooks=new Books();
        offset = BigDecimal.ZERO;
        maxCount = BigDecimal.ZERO;
        validPeriod = BigDecimal.ZERO;
        batchSize = BigDecimal.ZERO;
        batchInterval = BigDecimal.ZERO;
        sendAt = BigDecimal.ZERO;
    }

    public Date getSendDate() {
        return sendDate;
    }

    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    public BigDecimal getSendFrom() {
        return sendFrom;
    }

    public void setSendFrom(BigDecimal sendFrom) {
        this.sendFrom = sendFrom;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Books getAddressBooks() {
        return addressBooks;
    }

    public void setAddressBooks(Books addressBooks) {
        this.addressBooks = addressBooks;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public BigDecimal getValidPeriod() {
        return validPeriod;
    }

    public void setValidPeriod(BigDecimal validPeriod) {
        this.validPeriod = validPeriod;
    }

    public BigDecimal getOffset() {
        return offset;
    }

    public void setOffset(BigDecimal offset) {
        this.offset = offset;
    }

    public BigDecimal getMaxCount() {
        return maxCount;
    }

    public void setMaxCount(BigDecimal maxCount) {
        this.maxCount = maxCount;
    }

    public BigDecimal getBatchSize() {
        return batchSize;
    }

    public void setBatchSize(BigDecimal batchSize) {
        this.batchSize = batchSize;
    }

    public BigDecimal getBatchInterval() {
        return batchInterval;
    }

    public void setBatchInterval(BigDecimal batchInterval) {
        this.batchInterval = batchInterval;
    }

    public BigDecimal getSendAt() {
        return sendAt;
    }

    public void setSendAt(BigDecimal sendAt) {
        this.sendAt = sendAt;
    }

    public BigDecimal getUserID() {
        return userID;
    }

    public void setUserID(BigDecimal userID) {
        this.userID = userID;
    }

    public int getSmsCharSize() {
        return smsCharSize;
    }

    public void setSmsCharSize(int smsCharSize) {
        this.smsCharSize = smsCharSize;
    }

    public String getNumberCount() {
        return numberCount;
    }

    public void setNumberCount(String numberCount) {
        this.numberCount = numberCount;
    }

    @Override
    public String toString() {
        return "BulkSMS{" + "sendFrom=" + sendFrom + ", comment=" + comment + ", addressBooks=" + addressBooks.getAbid() + ", message=" + message + ", validPeriod=" + validPeriod + ", offset=" + offset + ", maxCount=" + maxCount + ", batchSize=" + batchSize + ", batchInterval=" + batchInterval + ", sendAt=" + sendAt + ", userID=" + userID + '}';
    }

}

src/java/send/sms/az/model/LogError.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package send.sms.az.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * @author rasha_000
 */
public class LogError extends BaseModel {

    private BigDecimal logID;
    private String LogType;
    private Date LogDate;
    private String LogText;
    private String AppName;
    private String Msisdn;

    public BigDecimal getLogID() {
        return logID;
    }

    public void setLogID(BigDecimal logID) {
        this.logID = logID;
    }

    public String getLogType() {
        return LogType;
    }

    public void setLogType(String LogType) {
        this.LogType = LogType;
    }

    public Date getLogDate() {
        return LogDate;
    }

    public void setLogDate(Date LogDate) {
        this.LogDate = LogDate;
    }

    public String getLogText() {
        return LogText;
    }

    public void setLogText(String LogText) {
        this.LogText = LogText;
    }

    public String getAppName() {
        return AppName;
    }

    public void setAppName(String AppName) {
        this.AppName = AppName;
    }

    public String getMsisdn() {
        return Msisdn;
    }

    public void setMsisdn(String Msisdn) {
        this.Msisdn = Msisdn;
    }

    @Override
    public String toString() {
        return "LogError{" + "logID=" + logID + ", LogType=" + LogType + ", LogDate=" + LogDate + ", LogText=" + LogText + ", AppName=" + AppName + ", Msisdn=" + Msisdn + '}';
    }
    
    
}

src/java/send/sms/az/web/BulkSMSController.java
package send.sms.az.web;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import org.apache.log4j.Logger;
import org.primefaces.model.LazyDataModel;
import org.primefaces.model.SortOrder;
import send.sms.az.dao.BulkSMSDao;
import send.sms.az.dao.UserLogDao;
import send.sms.az.model.Books;
import send.sms.az.model.BulkSMS;
import send.sms.az.model.ext.BulkSMSModel;
import send.sms.az.model.BulkSMSSend;
import send.sms.az.model.ScheduledModel;
import send.sms.az.util.FacesUtil;
import send.sms.az.util.LogTypes;
import send.sms.az.web.ext.UserDetails;

/**
 *
 * @author Rashad Javadov
 */
@ManagedBean(name = "bulksmsCnt")
@SessionScoped
public class BulkSMSController extends UserDetails implements Serializable {

    private static final Logger LOG = Logger.getLogger(BulkSMSController.class.getName());

    private LazyDataModel<BulkSMSSend> model;
    private BulkSMSDao bulkSMSDao;
    private BulkSMSModel bsmsm = new BulkSMSModel();
    private BulkSMSSend send = new BulkSMSSend();
    private BulkSMS bsms = new BulkSMS(); 
    private ScheduledModel scheduledModel = new ScheduledModel();

    public BulkSMSController() {
        bulkSMSDao=new BulkSMSDao();
    }

    @PostConstruct
    public void init() {//pagination for DataTable
        LOG.info("init() invoked");
        try {
            LOG.info("here1");
            this.model = new LazyDataModel<BulkSMSSend>() {
                private static final long serialVersionUID = 1L;

                @Override
                public List<BulkSMSSend> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, Object> filters) {
                    LOG.info("first " + first + " pageSize " + pageSize);
                    bsmsm.setStart(new BigDecimal(first));
                    bsmsm.setEnd(new BigDecimal(first + pageSize));
//                    ProtocolFilter.filterProtocolTable(filters, detailSearchModel);
                    bsmsm = bulkSMSDao.BulkSMSList(bsmsm);
                    model.setRowCount((int) bsmsm.getRowCount().intValue());
                    LOG.info("count " + model.getRowCount());
                    return bsmsm.getList();
                }
            };
        } catch (Exception e) {
            e.printStackTrace();
             userLogger.setType(LogTypes.BULKLIST.toString());
            userLogger.setDescription(e.getMessage());
            userLogger.setUserID(loginCnt.getUser().getUser_id());
            UserLogDao.insertUserLog(userLogger);
            LOG.info("exception occured " + e);
        }
    }

    public void countCharSize() {
        bsms.setSmsCharSize(bsms.getMessage().toString().getBytes().length);
        if (bsms.getSmsCharSize() == 160) {
            FacesUtil.addErrorMessage("Diqqət SMS sayi 2 ");
        }
    }

    public void tableListener(BigDecimal id) {
        bsms.setAddressBooks(new Books(id, ""));
    }

    public void openTempModal() {
        FacesUtil.createModal(400, 800, "modal/templTbl");
    }

    public void comfirmSMSsend() {
        LOG.info("comfirmSMSsend invoked " + bsms.getSendAt() + " " + bsms.getSendDate());
        try {
            if (bsms.getAddressBooks().getAbid().compareTo(BigDecimal.ZERO) != 0) {//addressbook
                if (bsms.getMessage() != null && !bsms.getMessage().equals("")) {//mesaj
                    boolean nullDate = false;
                    if (bsms.getSendAt() != null && bsms.getSendAt().compareTo(new BigDecimal(2)) == 0) {
                        if (bsms.getSendDate() == null) {
                            nullDate = true;
                            FacesUtil.addErrorMessage("Tarixi daxil edin");
                        }
                    }
                    if (bsms.getSendFrom() != null && bsms.getSendFrom().compareTo(BigDecimal.ZERO) != 0) {
                        if (!nullDate) {
                            FacesUtil.createModal(150, 180, "modal/confirmDetail");
                            //show details of bulk sms
                        } else {
                            FacesUtil.addErrorMessage("Tarixi daxil edin");
                        }
                    } else {
                        FacesUtil.addErrorMessage("Göndərəni daxil edin");
                    }
                } else {
                    FacesUtil.addErrorMessage("Mesajı daxil edin");
                }

            } else {
                FacesUtil.addErrorMessage("Address Book daxil edin");
            }
        } catch (Exception e) {
            e.printStackTrace();
            FacesUtil.addErrorMessage("Xəta baş verdi!");
            bsms = new BulkSMS();
        }

    }

    public void selectTemplate(String msg) {
        LOG.info("selectTemplate  ");
        bsms.setMessage(msg);
        bsms.setSmsCharSize(msg.getBytes().length);
        FacesUtil.closeDialog();
    }

    public void insertNewBulkSMS() {
        bsms.setUserID(loginCnt.getUser().getUser_id());
        try {
            LOG.info("SENDER_ID " + bsms.getSendFrom());
            bulkSMSDao.insertBulkSMS(bsms);
            FacesUtil.addInfoMessage("Uğurla qeydə alındı!");
            bsms = new BulkSMS();
        } catch (Exception e) {
            e.printStackTrace();
            userLogger.setType(LogTypes.INSERTBULK.toString());
            userLogger.setDescription(e.getMessage());
            userLogger.setUserID(loginCnt.getUser().getUser_id());
            UserLogDao.insertUserLog(userLogger);
            FacesUtil.addErrorMessage("Xəta baş verdi!");
            bsms = new BulkSMS();
        }
    }

    public BulkSMSModel getBsmsm() {
        return bsmsm;
    }

    public void setBsmsm(BulkSMSModel bsmsm) {
        this.bsmsm = bsmsm;
    }

    public BulkSMS getBsms() {
        return bsms;
    }

    public void setBsms(BulkSMS bsms) {
        this.bsms = bsms;
    }

    public LazyDataModel<BulkSMSSend> getModel() {
        return model;
    }

    public void setModel(LazyDataModel<BulkSMSSend> model) {
        this.model = model;
    }

    public BulkSMSSend getSend() {
        return send;
    }

    public void setSend(BulkSMSSend send) {
        this.send = send;
    } 
}

web/bulksms/tables/bulksmsTable.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head> 
        <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
        <title>Lsim</title> 
    </h:head> 
    <h:body>
        <h:form id="TblForm">
            <ui:include src="../taskDetails.xhtml"/>
            <p:dataTable style="font-size: 11px;" var="sms" rendered="#{!bulksmsCnt.bsmsm.showDetail}"  value="#{bulksmsCnt.model}" lazy="true"
                         rows="40"  widgetVar="myTblWidget" paginator="true" rowsPerPageTemplate="20,50,100,200" id="blacklisttable"
                         rowIndexVar="rowIndex" rowKey="#{sms.id}"  emptyMessage="Uyğun müəlumat tapılmadı"
                         paginatorTemplate="{CurrentPageReport} {PreviousPageLink} {PageLinks} {NextPageLink} {RowsPerPageDropdown}" >

                <!--<p:ajax event="rowSelect" listener="{smstmpCnt.listener()}" update=":detailForm"/>-->
                <p:column headerText="Comments"> 
                    <h:outputText value="#{sms.comments}" />
                </p:column>  
                <p:column  headerText="Send from"> 
                    <h:commandLink   onclick="updFrm()" value="#{sms.send_from}" action="#{taskCnt.recDetails(sms)}">
                        <!--<f:ajax  render="@form" />-->
                        <!--<p:ajax update="@form"  process="@this"/>-->
                    </h:commandLink>
                </p:column>  
                <p:column   headerText="Date Added"> 
                    <h:outputText value="#{sms.date_added}" />
                </p:column>  
                <p:column  headerText="Date Started"> 
                    <h:outputText value="#{sms.date_started}"/>
                </p:column>  
                <p:column   headerText="Added by"> 
                    <h:outputText value="#{sms.added_by}" />
                </p:column>  
                <p:column headerText="Count"> 
                    <h:outputText value="#{sms.number_count}" />
                </p:column> 
                <p:column  headerText="Wait For Status"> 
                    <h:outputText value="#{sms.wait4status}" />
                </p:column>
                <p:column  headerText="Delivery Count"> 
                    <h:outputText value="#{sms.delivCount}" />
                </p:column> 
                <p:column headerText="Undelivery Count"> 
                    <h:outputText value="#{sms.unDelivCount}" />
                </p:column> 
                <p:column  headerText="Queue Count"> 
                    <h:outputText value="#{sms.queueCount}" />
                </p:column> 
                <p:column  headerText="Error Count"> 
                    <h:outputText value="#{sms.errorCount}" />
                </p:column> 
                <p:column   headerText="BlackList Count"> 
                    <h:outputText value="#{sms.blaclListCount}" />
                </p:column> 
                <p:column headerText="Started"> 
                    <h:outputText value="#{sms.started}" />
                </p:column>
            </p:dataTable>
              <!--<h:outputScript library="javascript" name="jsf.js" target="head" />-->
              
              <p:remoteCommand name="updFrm" update="@form"/>
        </h:form>
      
    </h:body>
</html>

web/bulksms/tables/detailsTable.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head> 
        <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
        <title>Lsim</title> 
    </h:head> 
    <h:body> 
        <p:dataTable id="dsTable"  style="font-size: 11px;width: 80%" var="task" value="#{taskCnt.taskList}" 
                     rows="40"  widgetVar="myTblWidget" paginator="true" rowsPerPageTemplate="40"   emptyMessage="Uyğun müəlumat tapılmadı"
                     paginatorTemplate="{CurrentPageReport} {PreviousPageLink} {PageLinks} {NextPageLink} {RowsPerPageDropdown}" > 
            <p:column headerText="MSISDN"> 
                <h:outputText value="#{task.msisdn}" />
            </p:column>  
            <p:column  headerText="MSG BODY">  
                <h:outputText value="#{task.msg_body}" />
            </p:column>  
            <p:column   headerText="Date Added"> 
                <h:outputText value="#{task.dateAdded}" />
            </p:column>  
            <p:column   headerText="Status"> 
                <h:outputText value="#{task.status}" />
            </p:column>  
        </p:dataTable> 
    </h:body>
</html>